# Site settings
title: Ayman Osman
description: Building themes for ecommerce platforms, mainly Salla
baseurl: ""
url: "https://aymanc-137.github.io"

# Multi-language settings
languages: ["en", "ar"]
default_lang: en
exclude_from_localizations: ["assets"]

# Build settings
markdown: kramdown
theme: minima

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - propmpt.md
